In [49]:
import statsmodels.formula.api as smf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df= pd.read_csv("gen1016m.csv",skiprows= 2, nrows=7, header= None, dtype = datatypes, usecols= range(84))
df1 = df.T
df1.head()
df1.rename(columns={0:'month', 1: 'ng',2:'coal',3:'nuclear',4:'wind',5:'sgen', 6:'gasprice'}, inplace=True)
df1.head()
df1['month'] = df1['month'].astype('category')
df1['ng'] = df1['ng'].astype('float')
df1['coal'] = df1['coal'].astype('float')
df1['nuclear'] = df1['nuclear'].astype('float')
df1['wind'] = df1['wind'].astype('float')
df1['sgen'] = df1['sgen'].astype('float')
df1['gasprice'] = df1['gasprice'].astype('float')

df1.head(3)

df1.info()
df1['month'].nunique()# now correctly returns 12 !!!
# df1['month'].head(50)
#df1.dtype
#df1.shape()
df1.ng = df1.ng/1000
df1.coal = (df1.coal/1000).astype(int)
df1.nuclear = (df1.nuclear/1000).astype(int)
df1.wind = (df1.wind/1000).astype(int)
df1.sgen = (df1.sgen/1000).astype(int)
df1.head(10)
#DWW later add time and month (as temp) in important "str as datatype, convert to sategory (One-hot encoding?)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 84 entries, 0 to 83
Data columns (total 7 columns):
month       84 non-null category
ng          84 non-null float64
coal        84 non-null float64
nuclear     84 non-null float64
wind        84 non-null float64
sgen        84 non-null float64
gasprice    84 non-null float64
dtypes: category(1), float64(6)
memory usage: 5.1 KB

  month         ng   coal  nuclear  wind   sgen  gasprice
0   Jan   9595.342  10766     3452  1873  25688      6.98
1   Feb   8972.040   9220     3261  1585  23038      6.27
2   Mar   6299.307   8945     3694  2526  21466      5.47
3   Apr   8636.464   7878     1970  2584  21070      4.91
4   May  10405.143  10209     3704  2175  26493      4.96
5   Jun  12859.045  12022     3610  2398  30890      5.31
6   Jul  13853.452  12067     3754  1754  31430      5.34
7   Aug  17099.564  12476     3669  1561  34807      5.06
8   Sep  11745.790  11227     3641  1463  28077      4.61
9   Oct   7702.703  10298     3794  1729  23525      4.45

In [50]:
# df_with_dummies = pd.get_dummies( df, columns = cols_to_transform, drop_first= True )
# columns : list-like, default None: Column names in the DataFrame to be encoded. 
# If columns is None then all the columns with object or category dtype will be converted.
dfwD = pd.get_dummies( df1, columns = None, drop_first= True )
dfwD.head(3)

,ng,coal,nuclear,wind,sgen,gasprice,month_Aug,month_Dec,month_Feb,month_Jan,month_Jul,month_Jun,month_Mar,month_May,month_Nov,month_Oct,month_Sep
0,9595.342,10766,3452,1873,25688,6.98,0,0,0,1,0,0,0,0,0,0,0
1,8972.040,9220,3261,1585,23038,6.27,0,0,1,0,0,0,0,0,0,0,0
2,6299.307,8945,3694,2526,21466,5.47,0,0,0,0,0,0,1,0,0,0,0

In [57]:
# np.append(a, [7,8,9]) also np.array([[1,2,3],[4,5,6]]).tolist()
hr16 = [7340, 7393, 7397, 7350, 7376, 7380, 7447, 7383, 7376, 7407, 7276,7485]
hr15 = [7311, 7373, 7277, 7337, 7368, 7329, 7431, 7366, 7353, 7332, 7381,7357]
hr14 = [7511, 7548, 7616, 7642, 7459, 7484, 7476, 7418, 7396, 7436, 7434,7410]
hr13 = [7393, 7425, 7501, 7442, 7527, 7569, 7577, 7482, 7457, 7517, 7514,7510]
hr12 = [7393, 7425, 7501, 7442, 7527, 7569, 7577, 7482, 7457, 7517, 7514,7510]
hr11 = [7674, 7681, 7651, 7494, 7537, 7596, 7585, 7526, 7537, 7530, 7528, 7464]
hr10 = [7340, 7312, 7683, 8111, 7779, 7427, 7444, 7567, 7469, 7385, 7397,7495]
hr = np.array( hr10 + hr11 + hr12 + hr13+ hr14 + hr15 + hr16) # To be UPDATED for 2017 ten months plus 2009!!!
#hr.reshape(-1,1)
dfwD["hr"] = hr
dfwD["time"] = range(84)# adding the "time" variable: trend should be negative
dfwD.head(84)

,ng,coal,nuclear,wind,sgen,gasprice,month_Aug,month_Dec,month_Feb,month_Jan,month_Jul,month_Jun,month_Mar,month_May,month_Nov,month_Oct,month_Sep,hr,time
0,9595.342,10766,3452,1873,25688,6.98,0,0,0,1,0,0,0,0,0,0,0,7340,0
1,8972.040,9220,3261,1585,23038,6.27,0,0,1,0,0,0,0,0,0,0,0,7312,1
2,6299.307,8945,3694,2526,21466,5.47,0,0,0,0,0,0,1,0,0,0,0,7683,2
3,8636.464,7878,1970,2584,21070,4.91,0,0,0,0,0,0,0,0,0,0,0,8111,3
4,10405.143,10209,3704,2175,26493,4.96,0,0,0,0,0,0,0,1,0,0,0,7779,4
5,12859.045,12022,3610,2398,30890,5.31,0,0,0,0,0,1,0,0,0,0,0,7427,5
6,13853.452,12067,3754,1754,31430,5.34,0,0,0,0,1,0,0,0,0,0,0,7444,6
7,17099.564,12476,3669,1561,34807,5.06,1,0,0,0,0,0,0,0,0,0,0,7567,7
8,11745.790,11227,3641,1463,28077,4.61,0,0,0,0,0,0,0,0,0,0,1,7469,8
9,7702.703,10298,3794,1729,23525,4.45,0,0,0,0,0,0,0,0,0,1,0,7385,9
10,6807.746,9089,2936,2621,21454,4.55,0,0,0,0,0,0,0,0,1,0,0,7397,10
11,6755.840,10747,3844,2439,23787,5.68,0,1,0,0,0,0,0,0,0,0,0,7495,11
12,8274.815,11516,3786,1916,25493,5.66,0,0,0,1,0,0,0,0,0,0,0,7674,12
13,8099.740,9516,3472,2370,23459,5.29,0,0,1,0,0,0,0,0,0,0,0,7681,13
14,6159.054,9860,3808,2605,22432,4.84,0,0,0,0,0,0,1,0,0,0,0,7651,14
15,9248.681,10162,2022,2832,24265,5.03,0,0,0,0,0,0,0,0,0,0,0,7494,15
16,12040.233,11076,3380,2871,29368,5.04,0,0,0,0,0,0,0,1,0,0,0,7537,16
17,14115.112,12250,3645,3132,33143,5.20,0,0,0,0,0,1,0,0,0,0,0,7596,17
18,17601.161,12898,3461,1959,35920,5.13,0,0,0,0,1,0,0,0,0,0,0,7585,18
19,19502.681,12767,3593,1913,37776,4.85,1,0,0,0,0,0,0,0,0,0,0,7526,19
20,12893.431,11576,3659,1509,29639,4.71,0,0,0,0,0,0,0,0,0,0,1,7537,20
21,9054.919,9924,3091,2399,24469,4.49,0,0,0,0,0,0,0,0,0,1,0,7530,21
22,7761.002,8821,2912,2582,22076,4.26,0,0,0,0,0,0,0,0,1,0,0,7528,22
23,10038.465,9713,2813,2203,24768,4.18,0,1,0,0,0,0,0,0,0,0,0,7464,23
24,10170.076,7999,2820,2781,23771,3.82,0,0,0,1,0,0,0,0,0,0,0,7393,24
25,9568.994,7439,2635,2351,21995,3.46,0,0,1,0,0,0,0,0,0,0,0,7425,25
26,10326.702,7056,2768,3049,23201,3.09,0,0,0,0,0,0,1,0,0,0,0,7501,26
27,12636.643,5927,2807,2711,24082,2.81,0,0,0,0,0,0,0,0,0,0,0,7442,27
28,13530.993,8499,3802,2607,28440,3.05,0,0,0,0,0,0,0,1,0,0,0,7527,28
29,15351.573,10395,3654,2369,31771,3.21,0,0,0,0,0,1,0,0,0,0,0,7569,29
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54,15325.914,12538,3731,2429,34025,4.58,0,0,0,0,1,0,0,0,0,0,0,7476,54
55,17421.569,12140,3728,2274,35565,4.25,1,0,0,0,0,0,0,0,0,0,0,7418,55
56,14001.500,11152,3624,2024,30802,4.34,0,0,0,0,0,0,0,0,0,0,1,7396,56
57,12511.799,9173,2958,2737,27381,4.23,0,0,0,0,0,0,0,0,0,1,0,7436,57
58,9684.530,8379,2860,3712,24637,4.68,0,0,0,0,0,0,0,0,1,0,0,7434,58
59,10723.336,8484,3812,2925,25945,4.50,0,1,0,0,0,0,0,0,0,0,0,7410,59
60,13732.964,8557,3816,2673,28779,4.31,0,0,0,1,0,0,0,0,0,0,0,7311,60
61,11950.308,6663,3442,2972,25028,5.02,0,0,1,0,0,0,0,0,0,0,0,7373,61
62,13562.843,5556,3693,2336,25149,3.71,0,0,0,0,0,0,1,0,0,0,0,7277,62
63,12498.694,5693,2698,3668,24559,3.24,0,0,0,0,0,0,0,0,0,0,0,7337,63
64,12581.597,7779,3442,3997,27801,3.28,0,0,0,0,0,0,0,1,0,0,0,7368,64
65,15170.692,10499,3548,3049,32268,3.25,0,0,0,0,0,1,0,0,0,0,0,7329,65
66,18256.149,11030,3714,3766,36767,3.23,0,0,0,0,1,0,0,0,0,0,0,7431,66
67,18919.131,11011,3706,2943,36580,3.23,1,0,0,0,0,0,0,0,0,0,0,7366,67
68,15291.490,9978,3604,3085,31959,3.20,0,0,0,0,0,0,0,0,0,0,1,7353,68
69,13177.039,8351,2455,3379,27364,3.04,0,0,0,0,0,0,0,0,0,1,0,7332,69
70,10647.386,6504,2275,4393,23820,2.78,0,0,0,0,0,0,0,0,1,0,0,7381,70
71,12122.742,6027,2985,4522,25658,2.72,0,1,0,0,0,0,0,0,0,0,0,7357,71
72,12720.786,6853,3687,4099,27362,3.17,0,0,0,1,0,0,0,0,0,0,0,7340,72
73,10199.432,4997,3556,4685,23438,2.83,0,0,1,0,0,0,0,0,0,0,0,7393,73
74,11985.998,3135,3775,5207,24104,2.33,0,0,0,0,0,0,1,0,0,0,0,7397,74
75,12018.257,4752,3651,4407,24829,2.52,0,0,0,0,0,0,0,0,0,0,0,7350,75
76,13567.638,7295,2698,4737,28299,2.49,0,0,0,0,0,0,0,1,0,0,0,7376,76
77,15183.989,10952,3587,3463,33188,2.77,0,0,0,0,0,1,0,0,0,0,0,7380,77
78,17413.274,11743,3711,5265,38134,3.07,0,0,0,0,1,0,0,0,0,0,0,7447,78
79,17912.816,11310,3710,3412,36345,3.07,1,0,0,0,0,0,0,0,0,0,0,7383,79
80,14618.797,11103,3596,3637,32956,3.19,0,0,0,0,0,0,0,0,0,0,1,7376,80
81,10729.979,10447,3005,4981,29164,3.24,0,0,0,0,0,0,0,0,0,1,0,7407,81
82,8953.220,7908,3305,4250,24418,3.14,0,0,0,0,0,0,0,0,1,0,0,7276,82
83,8188.090,10605,3803,4995,27592,4.16,0,1,0,0,0,0,0,0,0,0,0,7485,83

In [65]:
### STATSMODELS ### # create a fitted model with all three features
import statsmodels.formula.api as smf
lm1 = smf.ols(formula = 'hr ~ ng + coal + nuclear + wind + sgen + gasprice + time + month_Jan + month_Feb + month_Mar + month_May + month_Jun + month_Jul + month_Aug + month_Sep + month_Oct + month_Nov + month_Dec', data=dfwD).fit()    
lm1.summary()# print a summary of the fitted model NB April seems the be the reference momth, as the highest hr

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     hr   R-squared:                       0.459
Model:                            OLS   Adj. R-squared:                  0.309
Method:                 Least Squares   F-statistic:                     3.058
Date:                Wed, 24 Jan 2018   Prob (F-statistic):           0.000501
Time:                        15:19:02   Log-Likelihood:                -496.73
No. Observations:                  84   AIC:                             1031.
Df Residuals:                      65   BIC:                             1078.
Df Model:                          18
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   7494.8481    251.861     29.758      0.000    6991.848    7997.848
ng            -5.1042     20.507     -0.249      0.804     -46.059      35.851
coal          -5.0739     20.505     -0.247      0.805     -46.026      35.878
nuclear       -5.1061     20.506     -0.249      0.804     -46.059      35.846
wind          -5.0690     20.507     -0.247      0.806     -46.023      35.885
sgen           5.0947     20.507      0.248      0.805     -35.860      46.050
gasprice       5.5806     19.834      0.281      0.779     -34.030      45.192
time          -2.2573      1.003     -2.251      0.028      -4.260      -0.255
month_Jan   -150.4548     70.879     -2.123      0.038    -292.011      -8.899
month_Feb   -106.2943     61.580     -1.726      0.089    -229.278      16.690
month_Mar    -31.9321     62.244     -0.513      0.610    -156.243      92.379
month_May    -52.4573     78.756     -0.666      0.508    -209.744     104.830
month_Jun    -91.1783    119.156     -0.765      0.447    -329.150     146.793
month_Jul    -49.5453    146.188     -0.339      0.736    -341.503     242.412
month_Aug    -59.2959    157.987     -0.375      0.709    -374.817     256.225
month_Sep   -103.2487    112.263     -0.920      0.361    -327.454     120.957
month_Oct   -118.2168     72.932     -1.621      0.110    -263.872      27.439
month_Nov   -124.7582     60.677     -2.056      0.044    -245.938      -3.578
month_Dec   -106.0518     72.334     -1.466      0.147    -250.513      38.410
==============================================================================
Omnibus:                       39.275   Durbin-Watson:                   1.141
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              206.700
Skew:                           1.248   Prob(JB):                     1.31e-45
Kurtosis:                      10.268   Cond. No.                     1.02e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.02e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [66]:
lm2 = smf.ols(formula = 'hr ~ ng + coal + nuclear + wind + gasprice + time + month_Jan + month_Feb + month_Mar + month_May + month_Jun + month_Jul + month_Aug + month_Sep + month_Oct + month_Nov + month_Dec', data=dfwD).fit()
lm2.summary()# print a summary of the fitted model after dropping sgen
# Oddly, April appears to be the reference month.
# Oddly, al eleven months are lower than this. DWW guess summer peak months should be the highest!?
# DWW: simply make a df of the monthly heat rates and create an index of the averages to investiogate this!?

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     hr   R-squared:                       0.458
Model:                            OLS   Adj. R-squared:                  0.318
Method:                 Least Squares   F-statistic:                     3.281
Date:                Wed, 24 Jan 2018   Prob (F-statistic):           0.000271
Time:                        15:19:57   Log-Likelihood:                -496.77
No. Observations:                  84   AIC:                             1030.
Df Residuals:                      66   BIC:                             1073.
Df Model:                          17
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   7501.1238    248.803     30.149      0.000    7004.372    7997.875
ng            -0.0095      0.012     -0.819      0.416      -0.032       0.014
coal           0.0204      0.017      1.221      0.227      -0.013       0.054
nuclear       -0.0118      0.033     -0.361      0.720      -0.077       0.053
wind           0.0256      0.025      1.007      0.318      -0.025       0.076
gasprice       5.8756     19.657      0.299      0.766     -33.371      45.122
time          -2.2360      0.992     -2.254      0.028      -4.216      -0.256
month_Jan   -148.6234     69.992     -2.123      0.037    -288.367      -8.880
month_Feb   -105.7792     61.106     -1.731      0.088    -227.782      16.223
month_Mar    -31.3837     61.762     -0.508      0.613    -154.695      91.927
month_May    -51.3703     78.074     -0.658      0.513    -207.249     104.509
month_Jun    -88.3793    117.776     -0.750      0.456    -323.527     146.769
month_Jul    -45.7143    144.335     -0.317      0.752    -333.889     242.460
month_Aug    -56.7984    156.542     -0.363      0.718    -369.344     255.747
month_Sep   -101.1695    111.152     -0.910      0.366    -323.092     120.753
month_Oct   -116.7637     72.179     -1.618      0.110    -260.873      27.346
month_Nov   -125.3912     60.191     -2.083      0.041    -245.566      -5.216
month_Dec   -104.1669     71.422     -1.458      0.149    -246.766      38.432
==============================================================================
Omnibus:                       40.553   Durbin-Watson:                   1.141
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              221.762
Skew:                           1.285   Prob(JB):                     7.00e-49
Kurtosis:                      10.533   Cond. No.                     5.07e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.07e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [67]:
lm3 = smf.ols(formula = 'hr ~ ng + coal + wind + gasprice + time + month_Jan + month_Feb + month_Mar + month_May + month_Jun + month_Jul + month_Aug + month_Sep + month_Oct + month_Nov + month_Dec', data=dfwD).fit()
lm3.summary()# print a summary of the fitted model after dropping sgen and nuclear

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     hr   R-squared:                       0.457
Model:                            OLS   Adj. R-squared:                  0.327
Method:                 Least Squares   F-statistic:                     3.524
Date:                Wed, 24 Jan 2018   Prob (F-statistic):           0.000145
Time:                        15:20:34   Log-Likelihood:                -496.86
No. Observations:                  84   AIC:                             1028.
Df Residuals:                      67   BIC:                             1069.
Df Model:                          16
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   7457.4378    215.898     34.542      0.000    7026.504    7888.372
ng            -0.0088      0.011     -0.774      0.442      -0.031       0.014
coal           0.0219      0.016      1.369      0.176      -0.010       0.054
wind           0.0265      0.025      1.050      0.297      -0.024       0.077
gasprice       4.5706     19.195      0.238      0.813     -33.743      42.884
time          -2.2788      0.978     -2.329      0.023      -4.232      -0.326
month_Jan   -161.7092     59.459     -2.720      0.008    -280.390     -43.028
month_Feb   -112.6982     57.638     -1.955      0.055    -227.743       2.347
month_Mar    -41.0394     55.292     -0.742      0.461    -151.403      69.324
month_May    -65.4752     67.128     -0.975      0.333    -199.462      68.512
month_Jun   -109.8572    100.942     -1.088      0.280    -311.339      91.625
month_Jul    -70.5455    126.022     -0.560      0.577    -322.087     180.996
month_Aug    -82.4745    138.501     -0.595      0.554    -358.924     193.975
month_Sep   -121.2649     95.546     -1.269      0.209    -311.975      69.445
month_Oct   -126.3919     66.621     -1.897      0.062    -259.369       6.585
month_Nov   -129.4589     58.739     -2.204      0.031    -246.703     -12.215
month_Dec   -117.4280     60.827     -1.931      0.058    -238.840       3.984
==============================================================================
Omnibus:                       42.206   Durbin-Watson:                   1.150
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              246.841
Skew:                           1.326   Prob(JB):                     2.51e-54
Kurtosis:                      10.968   Cond. No.                     4.17e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.17e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [68]:
lm4 = smf.ols(formula='hr ~ wind + gasprice + time', data=dfwD).fit()
lm4.summary()# print a summary of the fitted model

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     hr   R-squared:                       0.330
Model:                            OLS   Adj. R-squared:                  0.305
Method:                 Least Squares   F-statistic:                     13.12
Date:                Wed, 24 Jan 2018   Prob (F-statistic):           4.76e-07
Time:                        15:22:06   Log-Likelihood:                -505.70
No. Observations:                  84   AIC:                             1019.
Df Residuals:                      80   BIC:                             1029.
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   7416.8254     78.494     94.489      0.000    7260.618    7573.033
wind           0.0365      0.018      2.012      0.048       0.000       0.073
gasprice      19.1142     12.340      1.549      0.125      -5.444      43.673
time          -3.2039      0.738     -4.341      0.000      -4.673      -1.735
==============================================================================
Omnibus:                       38.600   Durbin-Watson:                   1.037
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              232.512
Skew:                           1.158   Prob(JB):                     3.24e-51
Kurtosis:                      10.815   Cond. No.                     2.18e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.18e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [ ]:
### STATSMODELS ###

In [ ]:
### STATSMODELS ###

# only include TV and Radio in the model # instantiate and fit model
lm1 = smf.ols(formula='Sales ~ TV + Radio', data=data).fit()
lm1.rsquared # calculate r-square

In [ ]:
import numpy as np
from sklearn import linear_model
y = heat_rates
X = df.values
reg = linear_model.LinearRegression()
reg.fit(X, y)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size = 0.3, random_state=42)
reg_all = linear_model.LinearRegression()
reg_all.fit(X_train, y_train)
y_pred = reg_all.predict(X_test)
reg_all.score(X_test, y_test)# returns R2

In [ ]:
from sklearn import linear_model
import numpy as np

X = np.random.rand(300,10)
y = np.random.rand(300,9)
reg = linear_model.LinearRegression()
reg.fit(X,y)